### ISSUE TITLE
missing image on assembly page

### ISSUE THREAD

**Issue by joostd** [makerdiary/m60#1]
The documentation on [assembling the M60](https://github.com/makerdiary/m60/blob/master/docs/assembling.md) has a reference to a [WebP file](https://wiki.makerdiary.com/nrf52840-m2-devkit/assets/images/attaching-antennas-to-m2.webp) that is not rendered in browsers lacking support for WebP (e.g. Safari).

Please convert to PNG like the other images referenced on this page.

**Comment by xiongyihui** [comment]
Thanks for reporting the issue. Just fixed.
